version: '3.8'

services:

  blue:
    image: vyshnavipriya/ci-cd-node:latest
    container_name: blue-app
    ports:
      - "3001:3000"
    environment:
      - ENV=BLUE

  green:
    image: vyshnavipriya/ci-cd-node:latest
    container_name: green-app
    ports:
      - "3002:3000"
    environment:
      - ENV=GREEN
