sonar.projectKey=ci-cd-blue-green
sonar.projectName=CI CD Blue Green Project
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://13.232.59.24:9000
sonar.login=squ_2cce44912e58c5870a061f20f1d0ad5797777dc8

sonar.exclusions=node_modules/**,coverage/**
