name: CI/CD Blue-Green + Production Pipeline

on:
  push:
    branches: ["main"]

jobs:

  # 🔹 1. BUILD & TEST
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test


  # 🔹 2. BUILD & PUSH DOCKER IMAGE
  docker:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-node:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-node:latest


  # 🔹 3. DEPLOY BLUE
  deploy-blue:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Blue Environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/ci-cd-node:latest

            docker pull $IMAGE

            docker stop blue-app || true
            docker rm blue-app || true

            docker run -d -p 3001:3000 --name blue-app $IMAGE

            echo "Blue deployed → http://<EC2-IP>:3001"


  # 🔹 4. DEPLOY GREEN
  deploy-green:
    needs: deploy-blue
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Green Environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/ci-cd-node:latest

            docker pull $IMAGE

            docker stop green-app || true
            docker rm green-app || true

            docker run -d -p 3002:3000 --name green-app $IMAGE

            echo "Green deployed → http://<EC2-IP>:3002"


  # 🔹 5. PRODUCTION (MANUAL APPROVAL REQUIRED)
  production:
    needs: deploy-green
    runs-on: ubuntu-latest

    environment:
      name: production   

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/ci-cd-node:latest

            docker pull $IMAGE

            docker stop prod-app || true
            docker rm prod-app || true

            docker run -d -p 3000:3000 --name prod-app $IMAGE

            echo "Production → http://<EC2-IP>:3000"
