name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  # 🔹 1. BUILD & TEST
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test


  # 🔹 2. BUILD & PUSH DOCKER IMAGE
  docker:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "vyshnavipriya" --password-stdin

      - name: Build Docker Image
        run: docker build -t vyshnavipriya/ci-cd-node:latest .

      - name: Push Docker Image
        run: docker push vyshnavipriya/ci-cd-node:latest


  # 🔹 3. DEPLOY TO EC2
  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull vyshnavipriya/ci-cd-node:latest
            docker stop app || true
            docker rm app || true
            docker run -d -p 3000:3000 --name app vyshnavipriya/ci-cd-node:latest
